name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  SCONSFLAGS_ARM64: ios_simulator=no verbose=yes warnings=extra werror=yes
  SCONSFLAGS_UNIVERSAL: ios_simulator=yes verbose=yes warnings=extra werror=yes

jobs:
  ios:
    runs-on: "macos-11"
    name: iOS Build ${{ matrix.target }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        shlibsuffix: [dylib]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build ${{ matrix.target }} arm64
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS_ARM64 }}
          arch: arm64
          platform: ios
          target: ${{ matrix.target }}

      - name: Build ${{ matrix.target }} universal
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS_UNIVERSAL }}
          arch: universal
          platform: ios
          target: ${{ matrix.target }}

      - name: Generate xcframework for ios
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
          SCONS_CACHE_LIMIT: 7168
        run: |
          xcodebuild -create-xcframework -library ./dist/addons/com.daylily_zeleen.hfsm2/bin/libhfsm2.ios.'${{ matrix.target }}'.a -library ./dist/addons/com.daylily_zeleen.hfsm2/bin/libhfsm2.ios.'${{ matrix.target }}'.simulator.a -output ./dist/addons/com.daylily_zeleen.hfsm2/bin/libhfsm2.ios.'${{ matrix.target }}'.xcframework
          xcodebuild -create-xcframework -library ./gdextension_dependencies/godot-cpp/bin/libgodot-cpp.ios.'${{ matrix.target }}'.arm64.a -library ./gdextension_dependencies/godot-cpp/bin/libgodot-cpp.ios.'${{ matrix.target }}'.universal.simulator.a  -output ./dist/addons/com.daylily_zeleen.hfsm2/bin/libgodot-cpp.ios.'${{ matrix.target }}'.xcframework

      - name: Upload ${{ matrix.target }} ${{ matrix.arch }}
        uses: ./.github/actions/upload
        with:
          platform: ios
          artifact_file_suffix: ios.${{ matrix.target }}.${{ matrix.arch }}.${{ matrix.shlibsuffix }}
