name: 🔗 Builds
# push, pull_request
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-build:
    name: 🤖 Android
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/macos_builds.yml
    secrets: inherit

  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web Builds
    uses: ./.github/workflows/web_builds.yml

  merge_artifacts:
    runs-on: ubuntu-latest
    needs: [android-build, ios-build, linux-build, macos-build, windows-build, web-build]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
            submodules: false

      - name: Setup version
        run: |
          echo BUILD_VERSION=$(head -n 1 ./version) >> $GITHUB_ENV

      - name: Merge Artifacts to all in one
        uses: actions/upload-artifact/merge@v4
        with:
            name: HFSM2-${{ env.BUILD_VERSION }}
            pattern: HFSM2-*
            delete-merged: true
            retention-days: 90
